# Use official Dev Spaces base 
FROM quay.io/devfile/universal-developer-image:ubi9-latest

USER root

# Add Kai mta core extension from GitHub release
RUN curl -L -o /konveyor-core-0.5.16.vsix https://github.com/konveyor/editor-extensions/releases/download/v0.5.16/konveyor-core-0.5.16.vsix
# Add Kai mta java extension from GitHub release
RUN curl -L -o /konveyor-java-0.5.16.vsix https://github.com/konveyor/editor-extensions/releases/download/v0.5.16/konveyor-java-0.5.16.vsix

# Add dependency Red Hat Java extension
RUN curl -L -o /redhat-java-extension-linux-x64.vsix https://github.com/redhat-developer/vscode-java/releases/download/v1.54.0/java-linux-x64-1.54.0-923.vsix

ENV DEFAULT_EXTENSIONS=/redhat-java-extension-linux-x64.vsix;/konveyor-core-0.5.16.vsix.vsix;/konveyor-java-0.5.16.vsix.vsix

USER user