# Use official Dev Spaces base 
FROM quay.io/devfile/universal-developer-image:ubi9-latest

USER root

# Add all Kai mta extensions from GitHub release
RUN curl -L -o /mta-core-8.1.2.vsix https://github.com/migtools/editor-extensions/releases/download/v8.1.2/mta-core-8.1.2.vsix
RUN curl -L -o /mta-java-8.1.2.vsix https://github.com/migtools/editor-extensions/releases/download/v8.1.2/mta-java-8.1.2.vsix
RUN curl -L -o /mta-csharp-8.1.2.vsix https://github.com/migtools/editor-extensions/releases/download/v8.1.2/mta-csharp-8.1.2.vsix
RUN curl -L -o /mta-go-8.1.2.vsix https://github.com/migtools/editor-extensions/releases/download/v8.1.2/mta-go-8.1.2.vsix
RUN curl -L -o /mta-javascript-8.1.2.vsix https://github.com/migtools/editor-extensions/releases/download/v8.1.2/mta-javascript-8.1.2.vsix
RUN curl -L -o /mta-vscode-extension-8.1.2.vsix https://github.com/migtools/editor-extensions/releases/download/v8.1.2/mta-vscode-extension-8.1.2.vsix


# Add dependency Red Hat Java extension
RUN curl -L -o /java-linux-x64-1.54.0-923.vsix https://github.com/redhat-developer/vscode-java/releases/download/v1.54.0/java-linux-x64-1.54.0-923.vsix

ENV DEFAULT_EXTENSIONS=/java-linux-x64-1.54.0-923.vsix;/redhat.mta-vscode-extension-8.1.2.vsix;mta-javascript-8.1.2.vsix;mta-go-8.1.2.vsix;mta-csharp-8.1.2.vsix;mta-java-8.1.2.vsix;mta-core-8.1.2.vsix

USER user