# Use official Dev Spaces base 
FROM quay.io/devfile/universal-developer-image:ubi9-latest

USER root

# Add Kai extension from GitHub release
RUN curl -L -o /mta-vscode-extension.vsix https://github.com/migtools/editor-extensions/releases/download/v8.0.5/mta-vscode-extension-8.0.5.vsix

ENV DEFAULT_EXTENSIONS=/mta-vscode-extension.vsix   

USER user